# Generated by Django 5.2.12 on 2026-03-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=' ', max_length=100)),
                ('type', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('delux', 'Delux')], max_length=100)),
                ('pricePerNight', models.IntegerField(default=1500)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=10)),
                ('maxOccupancy', models.IntegerField(default=1)),
                ('description', models.TextField()),
            ],
        ),
    ]
