# Generated by Django 5.2.12 on 2026-03-26 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='is_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='is_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
