# Generated by Django 5.2.10 on 2026-03-28 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupiedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupiedDate', to='rooms.rooms')),
            ],
        ),
    ]
